local _, MPT = ...
local L = LibStub("AceLocale-3.0"):GetLocale("MPlusTimer")
MPT.SeasonData = {
    [15] = {name =L["TWW S3"], Dungeons = {503, 505, 499, 525, 542, 378, 391, 392}},
    -- idk why there is a gap here but on Beta S1 is 17
    [17] = {name = L["Midnight S1"], Dungeons = {557, 558, 559, 560, 239, 402, 556, 161}},
    [18] = {name = L["Midnight S2"], Dungeons = {}},
    [19] = {name = L["Midnight S3"], Dungeons = {}},
    [20] = {name = L["TLT S1"], Dungeons = {}},
    [21] = {name = L["TLT S2"], Dungeons = {}},
    [22] = {name = L["TLT S3"], Dungeons = {}},
}

function MPT:GetDungeonName(cmap)
    local name = cmap and self.maptoID[cmap] and self.maptoID[cmap][2] or L["Unknown"]
    return self:Utf8Sub(name, 1, self.DungeonName.Shorten)
end

MPT.maptoID = { -- MapChallengeMode = JournalInstance
    -- Wrath of the Lich King
    [556] = {278, L["Pit of Saron"]},
    -- Cata
    [438] = {68, L["Vortex Pinnacle"]},
    [456] = {65, L["Throne"]},
    [507] = {71, L["Grim Batol"]},
    [541] = {67, L["Stonecore"]},
    -- MoP
    [2] =  {313, L["Jade Serpent"]},
    [56] = {302, L["Stromsout"]},
    [57] = {303, L["Setting Sun"]},
    [58] = {312, L["Shadow-Pan"]},
    [59] = {324, L["Niuzao"]},
    [60] = {321, L["Mogu'shan"]},
    [76] = {246, L["Scholomance"]},
    [77] = {311, L["Scarlet Halls"]},
    [78] = {316, L["Monastery"]},
    
    -- WoD
    [161] = {476, L["Skyreach"]},
    [163] = {385, L["Slag Mines"]},
    [164] = {547, L["Auchindoun"]},
    [165] = {537, L["Shadowmoon"]},
    [166] = {536, L["Grimrail"]},
    [167] = {559, L["UBRS"]},
    [168] = {556, L["Everbloom"]},
    [169] = {558, L["Iron Docks"]},
    
    -- Legion
    [197] = {716, L["Eye of Azshara"]},
    [198] = {762, L["Darkheart"]},
    [199] = {740, L["BRH"]},
    [200] = {721, L["Halls of Valor"]},
    [206] = {767, L["Neltharion's Lair"]},
    [207] = {707, L["Vault"]},
    [208] = {727, L["Maw of Souls"]},
    [209] = {726, L["Arcway"]},
    [210] = {800, L["Court of Stars"]},
    [227] = {860, L["Kara: Lower"]},
    [233] = {900, L["Cathedral"]},
    [234] = {860, L["Kara: Upper"]},
    [239] = {945, L["Seat"]},
    
    -- BfA
    [244] = {968, L["Atal'Dazar"]},
    [245] = {1001, L["Freehold"]},
    [246] = {1002, L["Tol Dagor"]},
    [247] = {1012, L["Motherlode"]},
    [248] = {1021, L["Waycrest"]},
    [249] = {1041, L["King's Rest"]},
    [250] = {1030, L["Sethraliss"]},
    [251] = {1022, L["Underrot"]},
    [252] = {1036, L["Shrine"]},
    [353] = {1023, L["Boralus"]},
    [369] = {1178, L["Junkyard"]},
    [370] = {1178, L["Workshop"]},
    
    -- Shadowlands
    [375] = {1184, L["Mists"]},
    [376] = {1182, L["Necrotic Wake"]},
    [377] = {1188, L["Other Side"]},
    [378] = {1185, L["Halls of Atonement"]},
    [379] = {1183, L["Plaguefall"]},
    [380] = {1189, L["Sanguine"]},
    [381] = {1186, L["Spires"]},
    [382] = {1187, L["Theater"]},
    [391] = {1194, L["Streets"]},
    [392] = {1194, L["Gambit"]},
    -- Dragonflight
    
    [399] = {1202, L["Ruby Pools"]},
    [400] = {1198, L["Nokhud"]},
    [401] = {1203, L["Azure Vault"]},
    [402] = {1201, L["Academy"]},
    [403] = {1197, L["Uldaman"]},
    [404] = {1199, L["Neltharus"]},
    [405] = {1196, L["Brackenhide"]},
    [406] = {1204, L["Halls"]},
    [463] = {1209, L["DotI: Lower"]},
    [464] = {1209, L["DotI: Upper"]},
    
    -- The War Within
    
    [499] = {1267, L["Priory"]},
    [500] = {1268, L["The Rookery"]},
    [501] = {1269, L["Stonevault"]},
    [502] = {1274, L["City of Threads"]},
    [503] = {1271, L["Ara-Kara"]},
    [504] = {1210, L["Darkflame Cleft"]},
    [505] = {1270, L["Dawnbreaker"]},
    [506] = {1272, L["Cinderbrew Meadery"]},
    [525] = {1298, L["Floodgate"]},
    [542] = {1303, L["Eco-Dome"]},

    -- Midnight

    [557] = {1299, L["Windrunner Spire"]},
    [558] = {1300, L["Magisters' Terrace"]},
    [559] = {1316, L["Nexus-Point"]},
    [560] = {1315, L["Maisara Caverns"]},

    --[[
    [0] = {1304, L["Murder Row"]},
    [0] = {1311, L["Den of Nalorakk"]},
    [0] = {1309, L["Blinding Vale"]},
    [0] = {1313, L["Voidscar Arena"]},
    ]]    
}

MPT.DefaultProfile = {
    Version = MPT:GetVersion(),
    name = L["default"],
    Spacing = 3,
    UpdateRate = 0.2,
    Scale = 1,
    HideTracker = true,
    FrameStrata = "HIGH",
    Background = {
        enabled = true,
        Color = {0, 0, 0, 0.5},
        WidthOffset = 0,
        HeightOffset = 0,
        xOffset = 0,
        yOffset = 0,
        BorderColor = {0, 0, 0, 1},
        BorderSize = 1,
    },
    Position = {
        xOffset = 0,
        yOffset = 250,
        Anchor = "RIGHT",
        relativeTo = "RIGHT",
    },
    KeyLevel = {
        enabled = true,
        Anchor = "LEFT",
        RelativeTo = "LEFT",
        xOffset = 0,
        yOffset = -2,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    DungeonName = {
        enabled = true,
        Anchor = "LEFT",
        RelativeTo = "LEFT",
        xOffset = 30,
        yOffset = -2,
        Font = "Expressway",
        FontSize = 16,
        Shorten = 14,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    AffixIcons = {
        enabled = false,
        Anchor = "CENTER",
        RelativeTo = "CENTER",
        xOffset = 2,
        yOffset = -2,
        Font = "Expressway",
        FontSize = 14,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    DeathCounter = {
        enabled = true,
        Iconenabled = true,
        ShowTimer = false,
        SquareBrackets = true,
        IconAnchor = "RIGHT",
        IconRelativeTo = "RIGHT",
        IconxOffset = 0,
        IconyOffset = 0,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = -16,
        yOffset = -1,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    KeyInfo = {
        AnchoredTo = "MainFrame",
        Anchor = "TOPLEFT",
        RelativeTo = "TOPLEFT",
        Width = 330,
        Height = 14,
        xOffset = 0,
        yOffset = 0,
    },
    TimerBar = {
        Anchor = "TOPLEFT",
        RelativeTo = "BOTTOMLEFT",
        AnchoredTo = "KeyInfo",
        Splits = true,        
        ChestTimerDisplay = 1, -- 1 == relevant timers. 2 == all timers. 3 = no timers
        Width = 330,
        Height = 24,
        xOffset = 0,
        yOffset = 0,
        Texture = "Details Flat",
        Color = {
            {89/255, 90/255, 92/255, 1},
            {1, 112/255, 0, 1},
            {1, 1, 0, 1},
            {128/255, 1, 0, 1},
        },
        BorderSize = 1,
        BackgroundColor = {0, 0, 0, 0.5},
        BorderColor = {0, 0, 0, 1},
    },
    TimerText = {
        enabled = true,
        Space = true,
        Anchor = "LEFT",
        RelativeTo = "LEFT",
        xOffset = 2,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Decimals = 1,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        SuccessColor = {1, 1, 0, 1},
        FailColor = {1, 0, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    ComparisonTimer = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "LEFT",
        xOffset = 0,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        SuccessColor = {0, 1, 0, 1},
        EqualColor = {1, 0.8, 0, 1},
        FailColor = {1, 0, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    ChestTimer1 = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = 0,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        BehindColor = {1, 0, 0, 1},
        AheadColor = {0, 1, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    ChestTimer2 = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = -65,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        BehindColor = {1, 0, 0, 1},
        AheadColor = {0, 1, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    ChestTimer3 = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = -130,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        BehindColor = {1, 0, 0, 1},
        AheadColor = {0, 1, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    Tick1 = {
        enabled = true,
        Width = 2,
        Color = {1, 1, 1, 1},
    },
    Tick2 = {
        enabled = true,
        Width = 2,
        Color = {1, 1, 1, 1},
    },
    Bosses = {
        Anchor = "TOPLEFT",
        RelativeTo = "BOTTOMLEFT",
        AnchoredTo = "TimerBar",
        Width = 330,
        Height = 16,
        xOffset = 0,
        yOffset = 0,
    },
    BossName = {
        enabled = true,
        Anchor = "LEFT",
        RelativeTo = "LEFT",
        MaxLength = 22,
        xOffset = 2,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        CompletionColor = {0, 1, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    BossTimer = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = 0,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
        SuccessColor = {0, 1, 0, 1},
        EqualColor = {1, 0.8, 0, 1},
        FailColor = {1, 0, 0, 1},
    },
    BossSplit = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = -70,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
        SuccessColor = {0, 1, 0, 1},
        EqualColor = {1, 0.8, 0, 1},
        FailColor = {1, 0, 0, 1},
    },
    PercentCount = {
        enabled = true,
        Anchor = "LEFT",
        RelativeTo = "LEFT",
        xOffset = 2,
        yOffset = 0,
        remaining = false,
        pullcount = true,
        afterPull = true,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        CurrentPullColor = {0, 1, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
        SquareBrackets = true,
    },
    RealCount = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = -1,
        yOffset = 0,
        Font = "Expressway",
        remaining = true,
        pullcount = true,
        afterPull = true,
        total = false,
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        CurrentPullColor = {0, 1, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
        SquareBrackets = true,
    },
    ForcesSplits = {
        enabled = true,
        Anchor = "LEFT",
        RelativeTo = "LEFT",
        xOffset = 60,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        SuccessColor = {0, 1, 0, 1},
        FailColor = {1, 0, 0, 1},
        EqualColor = {1, 1, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    ForcesCompletion = {
        enabled = true,
        Anchor = "LEFT",
        RelativeTo = "LEFT",
        xOffset = 2,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    ForcesBar = {
        Anchor = "TOPLEFT",
        RelativeTo = "BOTTOMLEFT",
        AnchoredTo = "Bosses",
        enabled = true,
        Width = 330,
        Height = 24,
        xOffset = 0,
        yOffset = 0,
        Texture = "Details Flat",
        PullText = true,
        Color = {
            {1, 117/255, 128/255, 1},
            {1, 130/255, 72/255, 1},
            {1, 197/255, 103/255, 1},
            {1, 249/255, 150/255, 1},
            {104/255, 205/255, 1, 1},
        },
        CompletionColor = {205/255, 1, 167/255, 1},
        BorderSize = 1,
        BackgroundColor = {0, 0, 0, 0.5},
        BorderColor = {0, 0, 0, 1},
    },
    
    PBInfo = {
        enabled = false,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        AnchoredTo = "ForcesBar",
        xOffset = 0,
        yOffset = -24,
        Font = "Expressway",
        Format = 1,  -- 1 == DD/MM/YY   2 == MM/DD/YY
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },

    CurrentPullBar = {
        enabled = true,
        Texture = "Details Flat",
        Color = {0, 1, 0, 1},
    },
}

MPT.AnchorTypes = {
    ["MainFrame"] = true,
    ["KeyInfo"] = true,
    ["TimerBar"] = true,
    ["Bosses"] = true,
    ["ForcesBar"] = true,
}

MPT.Gossips = {
    [196974] = {Name = L["Academy Crit Buff"], enabled = true, number = 1},
    [196977] = {Name = L["Academy Haste Buff"], enabled = true, number = 1}, 
    [196978] = {Name = L["Academy Mastery Buff"], enabled = true, number = 1},
    [196981] = {Name = L["Academy Versatility Buff"], enabled = true, number = 1},
    [196979] = {Name = L["Academy Healing Taken Buff"], enabled = true, number = 1},
        
    [97081] = {Name = L["HoV - King Bjorn"], enabled = true, number = 1},
    [95843] = {Name = L["HoV - King Haldor"], enabled = true, number = 1}, 
    [97083] = {Name = L["HoV - King Ranulf"], enabled = true, number = 1},
    [97084] = {Name = L["HoV - King Tor"], enabled = true, number = 1},
    [95676] = {Name = L["HoV - Odyn"], enabled = true, number = 1},

    [194602] = {Name = L["Azure Vault 1st Book"], enabled = true, number = 1},
    [194712] = {Name = L["Azure Vault 2nd Book"], enabled = true, number = 1}, 
    [194713] = {Name = L["Azure Vault 3rd Book"], enabled = true, number = 1},
    [194714] = {Name = L["Azure Vault 4th Book"], enabled = true, number = 1},
    [194715] = {Name = L["Azure Vault 5th Book"], enabled = true, number = 1},        

    [135978] = {Name = L["Freehold - Beer Event"], enabled = true, number = 1},
    [130086] = {Name = L["Davey"], enabled = true, number = 1}, 

    [194675] = {Name = L["Brackenhide - Alchemy Cauldron"], enabled = true, number = 1},

    [194675] = {Name = L["Halls of Infusion - Eng Buff"], enabled = true, number = 1},
    [197654] = {Name = L["Halls of Infusion - Infused Mushroom"], enabled = true, number = 1},
        
    [189219] = {Name = L["Neltharus - Qalashi Goulash"], enabled = true, number = 1},
    [189786] = {Name = L["Neltharus - Blazing Aegis"], enabled = true, number = 1},        

    [138761] = {Name = L["Waycrest Manor - Entrance Teleport"], enabled = true, number = 1},
        
    [105729] = {Name = L["Court of Stars - Lantern"], enabled = true, number = 1}, 
    [106468] = {Name = L["Court of Stars - Disguise"], enabled = true, number = 1},
    [107486] = {Name = L["Court of Stars - Clue"], enabled = true, number = 1},
    [105157] = {Name = L["Court of Stars - Engineering Orb"], enabled = true, number = 1},        
    [105117] = {Name = L["Court of Stars - Alchemy Flask"], enabled = true, number = 1}, 
    [106018] = {Name = L["Court of Stars - Bazaar Goods"], enabled = true, number = 1},
    [106113] = {Name = L["Court of Stars - Nightborne Statue"], enabled = true, number = 1},
    [105215] = {Name = L["Court of Stars - Discarded Junk"], enabled = true, number = 1},        
    [106112] = {Name = L["Court of Stars - Wounded Civilian"], enabled = true, number = 1}, 
    [105160] = {Name = L["Court of Stars - Fel Orb"], enabled = true, number = 1},
    [105831] = {Name = L["Court of Stars - Infernal Tome"], enabled = true, number = 1},
    [106024] = {Name = L["Court of Stars - Magical Lantern"], enabled = true, number = 1},
    [105249] = {Name = L["Court of Stars - Refreshments"], enabled = true, number = 1},        
    [106108] = {Name = L["Court of Stars - Rose Brew"], enabled = true, number = 1}, 
    [105340] = {Name = L["Court of Stars - Umbral Bloom"], enabled = true, number = 1},
    [106110] = {Name = L["Court of Stars - Waterlogged Scroll"], enabled = true, number = 1},

    [252789] = {Name = L["Pit of Saron - Quarry camps liberation"], enabled = true, number = 1},
}